services:
  db:
    image: postgres:16
    env_file: ./docker/db.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - ./backend/.env.docker
    environment:
      # help entrypoint wait for DB
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"


volumes:
  postgres_data:
