# Generated by Django 5.2.5 on 2025-09-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=15)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('APPOINTMENT', 'Appointment'), ('OFFER', 'Offer'), ('NOTICE', 'Notice'), ('OTHER', 'Other')], max_length=11)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=7)),
                ('provider_id', models.CharField(blank=True, max_length=100)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
