# Generated by Django 5.2.5 on 2025-09-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('address', models.TextField()),
                ('phones', models.CharField(max_length=100)),
                ('theme_config', models.JSONField(default=dict)),
                ('prescription_format', models.JSONField(default=dict)),
            ],
        ),
    ]
